version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/web.conf:ro
      - ./src:/src
      - ./data/log:/log
    ports:
      - "8000:8000"
    depends_on:
      - django
  django:
    build: .
    volumes:
      - ./src:/src
      - ./data/log:/log
      - ./engines:/engines
      - ./entrypoint:/entrypoint
    command: python manage.py runserver 0.0.0.0:6000
    entrypoint:
      - init
      - /entrypoint/managedocker.sh
    # Privileged is required to run docker inside docker
    privileged: true
    # Use the following command instead to use gunicorn which is closer to production, however isn't ideal for development due to caching
    #command: gunicorn openra.wsgi -w 10 -t 300 --log-file=/log/gunicorn.log -b 0.0.0.0:6000
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
