version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/web.conf:ro
      - ./src:/src
      - ./data/log:/log
    ports:
      - "9000:8000"
    depends_on:
      - django
  django:
    build: .
    volumes:
      - ./src:/src
      - ./data/log:/log
      - ./engines:/engines
      - ./libs:/libs
    privileged: true
    depends_on:
      - db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
